default_context:
  project_name: whitepaper
  repo_url: https://github.com/AllenInstitute/whitepaper
  project_slug: whitepaper
  user_name: nicholasc
  project_short_description: example
  project_namespace: ''
  version: 0.1.0
  full_name: Nicholas Cain
  _template: git@github.com:AllenInstitute/pyproject_template
  _copy_without_render:
  - docs/aibs_sphinx
  email: nicholasc@alleninstitute.org
